import { Media, User } from '.';
import { Classroom } from './classroom';
import { Family } from './family';
import { Grade } from './grade';
import { Prevschool } from './prevschool';

export type Student = {
  id: number;
  nisn: string;
  nis: string;
  name: string;
  gender: boolean;
  status: string;
  address: string;
  grade_id: number;
  classroom_id: number;
  phone: string;
  email: string;
  pob: string;
  dob: string;
  user_id: number;
  grade?: Grade;
  classroom?: Classroom;
  user?: User;
  kelahiran: string;
  umur: number;
  avatar: string;
  family?: Family;
  prevschool?: Prevschool;
  media?: Media[];
  created_at: string;
  updated_at?: string;
};
