import { Surah } from '@/types';

export const addressData = [
  // Balikpapan Selatan (7 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Damai Bahagia', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Damai Baru', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Gunung Bahagia', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan Baru', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan Raya', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sungai Nangka', kodepos: '76114' },

  // Balikpapan Kota (5 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Damai', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Klandasan Ilir', kodepos: '76113' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Klandasan Ulu', kodepos: '76112' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Prapatan', kodepos: '76111' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Telaga Sari', kodepos: '76111' },

  // Balikpapan Timur (4 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Manggar', kodepos: '76116' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Manggar Baru', kodepos: '76116' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Lamaru', kodepos: '76117' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Teritip', kodepos: '76118' },

  // Balikpapan Barat (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Ilir', kodepos: '76131' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Tengah', kodepos: '76132' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Ulu', kodepos: '76133' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Kariangau', kodepos: '76134' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Margasari', kodepos: '76131' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Margo Mulyo', kodepos: '76131' },

  // Balikpapan Utara (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Batu Ampar', kodepos: '76136' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Gunung Samarinda', kodepos: '76125' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Gunung Samarinda Baru', kodepos: '76128' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Karang Joang', kodepos: '76127' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Muara Rapak', kodepos: '76125' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Graha Indah', kodepos: '76129' },

  // Balikpapan Tengah (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Gunung Sari Ilir', kodepos: '76121' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Gunung Sari Ulu', kodepos: '76122' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Karang Jati', kodepos: '76123' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Karang Rejo', kodepos: '76124' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Mekar Sari', kodepos: '76122' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Sumber Rejo', kodepos: '76124' },
];

export const surahList: Surah[] = [
  { id: 1, surah: 'al-fatihah', ayat: 7, jenis: 'makiyah', juz: 1 },
  { id: 2, surah: 'al-baqarah', ayat: 286, jenis: 'madaniyah', juz: 1 },
  { id: 3, surah: "ali 'imran", ayat: 200, jenis: 'madaniyah', juz: 3 },
  { id: 4, surah: "an-nisaa'", ayat: 176, jenis: 'madaniyah', juz: 4 },
  { id: 5, surah: "al-ma'idah", ayat: 120, jenis: 'madaniyah', juz: 6 },
  { id: 6, surah: "al-an'am", ayat: 165, jenis: 'makiyah', juz: 7 },
  { id: 7, surah: "al-a'raf", ayat: 206, jenis: 'makiyah', juz: 8 },
  { id: 8, surah: 'al-anfal', ayat: 75, jenis: 'madaniyah', juz: 9 },
  { id: 9, surah: 'at-taubah', ayat: 129, jenis: 'madaniyah', juz: 10 },
  { id: 10, surah: 'yunus', ayat: 109, jenis: 'makiyah', juz: 11 },
  { id: 11, surah: 'hud', ayat: 123, jenis: 'makiyah', juz: 11 },
  { id: 12, surah: 'yusuf', ayat: 111, jenis: 'makiyah', juz: 12 },
  { id: 13, surah: 'ar-ra’d', ayat: 43, jenis: 'makiyah', juz: 13 },
  { id: 14, surah: 'ibrahim', ayat: 52, jenis: 'makiyah', juz: 13 },
  { id: 15, surah: 'al-hijr', ayat: 99, jenis: 'makiyah', juz: 14 },
  { id: 16, surah: 'an-nahl', ayat: 128, jenis: 'makiyah', juz: 14 },
  { id: 17, surah: "al-isra'", ayat: 111, jenis: 'makiyah', juz: 15 },
  { id: 18, surah: 'al-kahf', ayat: 110, jenis: 'makiyah', juz: 15 },
  { id: 19, surah: 'maryam', ayat: 98, jenis: 'makiyah', juz: 16 },
  { id: 20, surah: 'ta ha', ayat: 135, jenis: 'makiyah', juz: 16 },
  { id: 21, surah: "al-anbiya'", ayat: 112, jenis: 'makiyah', juz: 17 },
  { id: 22, surah: 'al-hajj', ayat: 78, jenis: 'madaniyah', juz: 17 },
  { id: 23, surah: 'al-mu’minun', ayat: 118, jenis: 'makiyah', juz: 18 },
  { id: 24, surah: 'an-nur', ayat: 64, jenis: 'madaniyah', juz: 18 },
  { id: 25, surah: 'al-furqan', ayat: 77, jenis: 'makiyah', juz: 19 },
  { id: 26, surah: 'asy-syu’ara', ayat: 227, jenis: 'makiyah', juz: 19 },
  { id: 27, surah: 'an-naml', ayat: 93, jenis: 'makiyah', juz: 19 },
  { id: 28, surah: 'al-qasas', ayat: 88, jenis: 'makiyah', juz: 20 },
  { id: 29, surah: 'al-ankabut', ayat: 69, jenis: 'makiyah', juz: 20 },
  { id: 30, surah: 'ar-rum', ayat: 60, jenis: 'makiyah', juz: 21 },
  { id: 31, surah: 'luqman', ayat: 34, jenis: 'makiyah', juz: 21 },
  { id: 32, surah: 'as-sajdah', ayat: 30, jenis: 'makiyah', juz: 21 },
  { id: 33, surah: 'al-ahzab', ayat: 73, jenis: 'madaniyah', juz: 21 },
  { id: 34, surah: "saba'", ayat: 54, jenis: 'makiyah', juz: 22 },
  { id: 35, surah: 'fatir', ayat: 45, jenis: 'makiyah', juz: 22 },
  { id: 36, surah: 'ya-sin', ayat: 83, jenis: 'makiyah', juz: 22 },
  { id: 37, surah: 'as-saffat', ayat: 182, jenis: 'makiyah', juz: 23 },
  { id: 38, surah: 'sad', ayat: 88, jenis: 'makiyah', juz: 23 },
  { id: 39, surah: 'az-zumar', ayat: 75, jenis: 'makiyah', juz: 23 },
  { id: 40, surah: 'ghafir', ayat: 85, jenis: 'makiyah', juz: 24 },
  { id: 41, surah: 'fussilat', ayat: 54, jenis: 'makiyah', juz: 24 },
  { id: 42, surah: 'asy-syura', ayat: 53, jenis: 'makiyah', juz: 25 },
  { id: 43, surah: 'az-zukhruf', ayat: 89, jenis: 'makiyah', juz: 25 },
  { id: 44, surah: 'ad-dukhan', ayat: 59, jenis: 'makiyah', juz: 25 },
  { id: 45, surah: 'al-jatsiyah', ayat: 37, jenis: 'makiyah', juz: 25 },
  { id: 46, surah: 'al-ahqaf', ayat: 35, jenis: 'makiyah', juz: 26 },
  { id: 47, surah: 'muhammad', ayat: 38, jenis: 'madaniyah', juz: 26 },
  { id: 48, surah: 'al-fath', ayat: 29, jenis: 'madaniyah', juz: 26 },
  { id: 49, surah: 'al-hujurat', ayat: 18, jenis: 'madaniyah', juz: 26 },
  { id: 50, surah: 'qaf', ayat: 45, jenis: 'makiyah', juz: 26 },
  { id: 51, surah: 'adz-dzariyat', ayat: 60, jenis: 'makiyah', juz: 27 },
  { id: 52, surah: 'at-tur', ayat: 49, jenis: 'makiyah', juz: 27 },
  { id: 53, surah: 'an-najm', ayat: 62, jenis: 'makiyah', juz: 27 },
  { id: 54, surah: 'al-qamar', ayat: 55, jenis: 'makiyah', juz: 27 },
  { id: 55, surah: 'ar-rahman', ayat: 78, jenis: 'madaniyah', juz: 27 },
  { id: 56, surah: 'al-waqi’ah', ayat: 96, jenis: 'makiyah', juz: 27 },
  { id: 57, surah: 'al-hadid', ayat: 29, jenis: 'madaniyah', juz: 27 },
  { id: 58, surah: 'al-mujadilah', ayat: 22, jenis: 'madaniyah', juz: 28 },
  { id: 59, surah: 'al-hasyr', ayat: 24, jenis: 'madaniyah', juz: 28 },
  { id: 60, surah: 'al-mumtahanah', ayat: 13, jenis: 'madaniyah', juz: 28 },
  { id: 61, surah: 'as-saff', ayat: 14, jenis: 'madaniyah', juz: 28 },
  { id: 62, surah: 'al-jumu’ah', ayat: 11, jenis: 'madaniyah', juz: 28 },
  { id: 63, surah: 'al-munafiqun', ayat: 11, jenis: 'madaniyah', juz: 28 },
  { id: 64, surah: 'at-taghabun', ayat: 18, jenis: 'madaniyah', juz: 28 },
  { id: 65, surah: 'at-talaq', ayat: 12, jenis: 'madaniyah', juz: 28 },
  { id: 66, surah: 'at-tahrim', ayat: 12, jenis: 'madaniyah', juz: 28 },
  { id: 67, surah: 'al-mulk', ayat: 30, jenis: 'makiyah', juz: 29 },
  { id: 68, surah: 'al-qalam', ayat: 52, jenis: 'makiyah', juz: 29 },
  { id: 69, surah: 'al-haqqah', ayat: 52, jenis: 'makiyah', juz: 29 },
  { id: 70, surah: 'al-ma’arij', ayat: 44, jenis: 'makiyah', juz: 29 },
  { id: 71, surah: 'nuh', ayat: 28, jenis: 'makiyah', juz: 29 },
  { id: 72, surah: 'al-jinn', ayat: 28, jenis: 'makiyah', juz: 29 },
  { id: 73, surah: 'al-muzzammil', ayat: 20, jenis: 'makiyah', juz: 29 },
  { id: 74, surah: 'al-muddatstsir', ayat: 56, jenis: 'makiyah', juz: 29 },
  { id: 75, surah: 'al-qiyamah', ayat: 40, jenis: 'makiyah', juz: 29 },
  { id: 76, surah: 'al-insan', ayat: 31, jenis: 'madaniyah', juz: 29 },
  { id: 77, surah: 'al-mursalat', ayat: 50, jenis: 'makiyah', juz: 29 },
  { id: 78, surah: "an-naba'", ayat: 40, jenis: 'makiyah', juz: 30 },
  { id: 79, surah: 'an-nazi’at', ayat: 46, jenis: 'makiyah', juz: 30 },
  { id: 80, surah: '‘abasa', ayat: 42, jenis: 'makiyah', juz: 30 },
  { id: 81, surah: 'at-takwir', ayat: 29, jenis: 'makiyah', juz: 30 },
  { id: 82, surah: 'al-infitar', ayat: 19, jenis: 'makiyah', juz: 30 },
  { id: 83, surah: 'al-mutaffifin', ayat: 36, jenis: 'makiyah', juz: 30 },
  { id: 84, surah: 'al-insyiqaq', ayat: 25, jenis: 'makiyah', juz: 30 },
  { id: 85, surah: 'al-buruj', ayat: 22, jenis: 'makiyah', juz: 30 },
  { id: 86, surah: 'at-tariq', ayat: 17, jenis: 'makiyah', juz: 30 },
  { id: 87, surah: 'al-a’la', ayat: 19, jenis: 'makiyah', juz: 30 },
  { id: 88, surah: 'al-ghasyiyah', ayat: 26, jenis: 'makiyah', juz: 30 },
  { id: 89, surah: 'al-fajr', ayat: 30, jenis: 'makiyah', juz: 30 },
  { id: 90, surah: 'al-balad', ayat: 20, jenis: 'makiyah', juz: 30 },
  { id: 91, surah: 'asy-syams', ayat: 15, jenis: 'makiyah', juz: 30 },
  { id: 92, surah: 'al-lail', ayat: 21, jenis: 'makiyah', juz: 30 },
  { id: 93, surah: 'ad-duha', ayat: 11, jenis: 'makiyah', juz: 30 },
  { id: 94, surah: 'asy-syarh', ayat: 8, jenis: 'makiyah', juz: 30 },
  { id: 95, surah: 'at-tin', ayat: 8, jenis: 'makiyah', juz: 30 },
  { id: 96, surah: 'al-‘alaq', ayat: 19, jenis: 'makiyah', juz: 30 },
  { id: 97, surah: 'al-qadr', ayat: 5, jenis: 'makiyah', juz: 30 },
  { id: 98, surah: 'al-bayyinah', ayat: 8, jenis: 'madaniyah', juz: 30 },
  { id: 99, surah: 'az-zalzalah', ayat: 8, jenis: 'madaniyah', juz: 30 },
  { id: 100, surah: 'al-adiyat', ayat: 11, jenis: 'makiyah', juz: 30 },
  { id: 101, surah: 'al-qari’ah', ayat: 11, jenis: 'makiyah', juz: 30 },
  { id: 102, surah: 'at-takatsur', ayat: 8, jenis: 'makiyah', juz: 30 },
  { id: 103, surah: 'al-‘asr', ayat: 3, jenis: 'makiyah', juz: 30 },
  { id: 104, surah: 'al-humazah', ayat: 9, jenis: 'makiyah', juz: 30 },
  { id: 105, surah: 'al-fil', ayat: 5, jenis: 'makiyah', juz: 30 },
  { id: 106, surah: 'quraisy', ayat: 4, jenis: 'makiyah', juz: 30 },
  { id: 107, surah: 'al-ma’un', ayat: 7, jenis: 'makiyah', juz: 30 },
  { id: 108, surah: 'al-kautsar', ayat: 3, jenis: 'makiyah', juz: 30 },
  { id: 109, surah: 'al-kafirun', ayat: 6, jenis: 'makiyah', juz: 30 },
  { id: 110, surah: 'an-nasr', ayat: 3, jenis: 'madaniyah', juz: 30 },
  { id: 111, surah: 'al-lahab', ayat: 5, jenis: 'makiyah', juz: 30 },
  { id: 112, surah: 'al-ikhlas', ayat: 4, jenis: 'makiyah', juz: 30 },
  { id: 113, surah: 'al-falaq', ayat: 5, jenis: 'makiyah', juz: 30 },
  { id: 114, surah: 'an-nas', ayat: 6, jenis: 'makiyah', juz: 30 },
];
