import { Surah } from '@/types';
import { PenilaianDoaHadist } from '@/types/report';

export const addressData = [
  // Balikpapan Selatan (7 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Damai Bahagia', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Damai Baru', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Gunung Bahagia', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan Baru', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sepinggan Raya', kodepos: '76115' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Selatan', kelurahan: 'Sungai Nangka', kodepos: '76114' },

  // Balikpapan Kota (5 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Damai', kodepos: '76114' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Klandasan Ilir', kodepos: '76113' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Klandasan Ulu', kodepos: '76112' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Prapatan', kodepos: '76111' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Kota', kelurahan: 'Telaga Sari', kodepos: '76111' },

  // Balikpapan Timur (4 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Manggar', kodepos: '76116' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Manggar Baru', kodepos: '76116' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Lamaru', kodepos: '76117' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Timur', kelurahan: 'Teritip', kodepos: '76118' },

  // Balikpapan Barat (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Ilir', kodepos: '76131' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Tengah', kodepos: '76132' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Baru Ulu', kodepos: '76133' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Kariangau', kodepos: '76134' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Margasari', kodepos: '76131' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Barat', kelurahan: 'Margo Mulyo', kodepos: '76131' },

  // Balikpapan Utara (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Batu Ampar', kodepos: '76136' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Gunung Samarinda', kodepos: '76125' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Gunung Samarinda Baru', kodepos: '76128' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Karang Joang', kodepos: '76127' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Muara Rapak', kodepos: '76125' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Utara', kelurahan: 'Graha Indah', kodepos: '76129' },

  // Balikpapan Tengah (6 kelurahan)
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Gunung Sari Ilir', kodepos: '76121' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Gunung Sari Ulu', kodepos: '76122' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Karang Jati', kodepos: '76123' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Karang Rejo', kodepos: '76124' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Mekar Sari', kodepos: '76122' },
  { provinsi: 'Kalimantan Timur', kabupaten: 'Balikpapan', kecamatan: 'Balikpapan Tengah', kelurahan: 'Sumber Rejo', kodepos: '76124' },
];

export const surahList: Surah[] = [
  { id: 1, surah: 'Al Fatihah (1)', ayat: 7, jenis: 'Makiyah', juz: 1 },
  { id: 2, surah: 'Al Baqarah (2)', ayat: 286, jenis: 'Madaniyah', juz: 1 },
  { id: 3, surah: "Ali 'Imran (3)", ayat: 200, jenis: 'Madaniyah', juz: 3 },
  { id: 4, surah: "An Nisaa' (4)", ayat: 176, jenis: 'Madaniyah', juz: 4 },
  { id: 5, surah: "Al Ma'idah (5)", ayat: 120, jenis: 'Madaniyah', juz: 6 },
  { id: 6, surah: "Al An'am (6)", ayat: 165, jenis: 'Makiyah', juz: 7 },
  { id: 7, surah: "Al A'raf (7)", ayat: 206, jenis: 'Makiyah', juz: 8 },
  { id: 8, surah: 'Al Anfal (8)', ayat: 75, jenis: 'Madaniyah', juz: 9 },
  { id: 9, surah: 'At Taubah (9)', ayat: 129, jenis: 'Madaniyah', juz: 10 },
  { id: 10, surah: 'Yunus (10)', ayat: 109, jenis: 'Makiyah', juz: 11 },
  { id: 11, surah: 'Hud (11)', ayat: 123, jenis: 'Makiyah', juz: 11 },
  { id: 12, surah: 'Yusuf (12)', ayat: 111, jenis: 'Makiyah', juz: 12 },
  { id: 13, surah: 'Ar Ra’d (13)', ayat: 43, jenis: 'Makiyah', juz: 13 },
  { id: 14, surah: 'Ibrahim (14)', ayat: 52, jenis: 'Makiyah', juz: 13 },
  { id: 15, surah: 'Al Hijr (15)', ayat: 99, jenis: 'Makiyah', juz: 14 },
  { id: 16, surah: 'An Nahl (16)', ayat: 128, jenis: 'Makiyah', juz: 14 },
  { id: 17, surah: "Al Isra' (17)", ayat: 111, jenis: 'Makiyah', juz: 15 },
  { id: 18, surah: 'Al Kahf (18)', ayat: 110, jenis: 'Makiyah', juz: 15 },
  { id: 19, surah: 'Maryam (19)', ayat: 98, jenis: 'Makiyah', juz: 16 },
  { id: 20, surah: 'Ta Ha (20)', ayat: 135, jenis: 'Makiyah', juz: 16 },
  { id: 21, surah: "Al Anbiya' (21)", ayat: 112, jenis: 'Makiyah', juz: 17 },
  { id: 22, surah: 'Al Hajj (22)', ayat: 78, jenis: 'Madaniyah', juz: 17 },
  { id: 23, surah: 'Al Mu’minun (23)', ayat: 118, jenis: 'Makiyah', juz: 18 },
  { id: 24, surah: 'An Nur (24)', ayat: 64, jenis: 'Madaniyah', juz: 18 },
  { id: 25, surah: 'Al Furqan (25)', ayat: 77, jenis: 'Makiyah', juz: 19 },
  { id: 26, surah: 'Asy Syu’ara (26)', ayat: 227, jenis: 'Makiyah', juz: 19 },
  { id: 27, surah: 'An Naml (27)', ayat: 93, jenis: 'Makiyah', juz: 19 },
  { id: 28, surah: 'Al Qasas (28)', ayat: 88, jenis: 'Makiyah', juz: 20 },
  { id: 29, surah: 'Al Ankabut (29)', ayat: 69, jenis: 'Makiyah', juz: 20 },
  { id: 30, surah: 'Ar Rum (30)', ayat: 60, jenis: 'Makiyah', juz: 21 },
  { id: 31, surah: 'Luqman (31)', ayat: 34, jenis: 'Makiyah', juz: 21 },
  { id: 32, surah: 'As Sajdah (32)', ayat: 30, jenis: 'Makiyah', juz: 21 },
  { id: 33, surah: 'Al Ahzab (33)', ayat: 73, jenis: 'Madaniyah', juz: 21 },
  { id: 34, surah: "Saba' (34)", ayat: 54, jenis: 'Makiyah', juz: 22 },
  { id: 35, surah: 'Fatir (35)', ayat: 45, jenis: 'Makiyah', juz: 22 },
  { id: 36, surah: 'Ya Sin (36)', ayat: 83, jenis: 'Makiyah', juz: 22 },
  { id: 37, surah: 'As Saffat (37)', ayat: 182, jenis: 'Makiyah', juz: 23 },
  { id: 38, surah: 'Sad (38)', ayat: 88, jenis: 'Makiyah', juz: 23 },
  { id: 39, surah: 'Az Zumar (39)', ayat: 75, jenis: 'Makiyah', juz: 23 },
  { id: 40, surah: 'Ghafir (40)', ayat: 85, jenis: 'Makiyah', juz: 24 },
  { id: 41, surah: 'Fussilat (41)', ayat: 54, jenis: 'Makiyah', juz: 24 },
  { id: 42, surah: 'Asy Syura (42)', ayat: 53, jenis: 'Makiyah', juz: 25 },
  { id: 43, surah: 'Az Zukhruf (43)', ayat: 89, jenis: 'Makiyah', juz: 25 },
  { id: 44, surah: 'Ad Dukhan (44)', ayat: 59, jenis: 'Makiyah', juz: 25 },
  { id: 45, surah: 'Al Jatsiyah (45)', ayat: 37, jenis: 'Makiyah', juz: 25 },
  { id: 46, surah: 'Al Ahqaf (46)', ayat: 35, jenis: 'Makiyah', juz: 26 },
  { id: 47, surah: 'Muhammad (47)', ayat: 38, jenis: 'Madaniyah', juz: 26 },
  { id: 48, surah: 'Al Fath (48)', ayat: 29, jenis: 'Madaniyah', juz: 26 },
  { id: 49, surah: 'Al Hujurat (49)', ayat: 18, jenis: 'Madaniyah', juz: 26 },
  { id: 50, surah: 'Qaf (50)', ayat: 45, jenis: 'Makiyah', juz: 26 },
  { id: 51, surah: 'Adz Dzariyat (51)', ayat: 60, jenis: 'Makiyah', juz: 27 },
  { id: 52, surah: 'At Tur (52)', ayat: 49, jenis: 'Makiyah', juz: 27 },
  { id: 53, surah: 'An Najm (53)', ayat: 62, jenis: 'Makiyah', juz: 27 },
  { id: 54, surah: 'Al Qamar (54)', ayat: 55, jenis: 'Makiyah', juz: 27 },
  { id: 55, surah: 'Ar Rahman (55)', ayat: 78, jenis: 'Madaniyah', juz: 27 },
  { id: 56, surah: 'Al Waqi’ah (56)', ayat: 96, jenis: 'Makiyah', juz: 27 },
  { id: 57, surah: 'Al Hadid (57)', ayat: 29, jenis: 'Madaniyah', juz: 27 },
  { id: 58, surah: 'Al Mujadilah (58)', ayat: 22, jenis: 'Madaniyah', juz: 28 },
  { id: 59, surah: 'Al Hasyr (59)', ayat: 24, jenis: 'Madaniyah', juz: 28 },
  { id: 60, surah: 'Al Mumtahanah (60)', ayat: 13, jenis: 'Madaniyah', juz: 28 },
  { id: 61, surah: 'As Saff (61)', ayat: 14, jenis: 'Madaniyah', juz: 28 },
  { id: 62, surah: 'Al Jumu’ah (62)', ayat: 11, jenis: 'Madaniyah', juz: 28 },
  { id: 63, surah: 'Al Munafiqun (63)', ayat: 11, jenis: 'Madaniyah', juz: 28 },
  { id: 64, surah: 'At Taghabun (64)', ayat: 18, jenis: 'Madaniyah', juz: 28 },
  { id: 65, surah: 'At Talaq (65)', ayat: 12, jenis: 'Madaniyah', juz: 28 },
  { id: 66, surah: 'At Tahrim (66)', ayat: 12, jenis: 'Madaniyah', juz: 28 },
  { id: 67, surah: 'Al Mulk (67)', ayat: 30, jenis: 'Makiyah', juz: 29 },
  { id: 68, surah: 'Al Qalam (68)', ayat: 52, jenis: 'Makiyah', juz: 29 },
  { id: 69, surah: 'Al Haqqah (69)', ayat: 52, jenis: 'Makiyah', juz: 29 },
  { id: 70, surah: 'Al Ma’arij (70)', ayat: 44, jenis: 'Makiyah', juz: 29 },
  { id: 71, surah: 'Nuh (71)', ayat: 28, jenis: 'Makiyah', juz: 29 },
  { id: 72, surah: 'Al Jinn (72)', ayat: 28, jenis: 'Makiyah', juz: 29 },
  { id: 73, surah: 'Al Muzzammil (73)', ayat: 20, jenis: 'Makiyah', juz: 29 },
  { id: 74, surah: 'Al Muddatstsir (74)', ayat: 56, jenis: 'Makiyah', juz: 29 },
  { id: 75, surah: 'Al Qiyamah (75)', ayat: 40, jenis: 'Makiyah', juz: 29 },
  { id: 76, surah: 'Al Insan (76)', ayat: 31, jenis: 'Madaniyah', juz: 29 },
  { id: 77, surah: 'Al Mursalat (77)', ayat: 50, jenis: 'Makiyah', juz: 29 },
  { id: 78, surah: "An Naba' (78)", ayat: 40, jenis: 'Makiyah', juz: 30 },
  { id: 79, surah: 'An Nazi’at (79)', ayat: 46, jenis: 'Makiyah', juz: 30 },
  { id: 80, surah: '‘Abasa (80)', ayat: 42, jenis: 'Makiyah', juz: 30 },
  { id: 81, surah: 'At Takwir (81)', ayat: 29, jenis: 'Makiyah', juz: 30 },
  { id: 82, surah: 'Al Infitar (82)', ayat: 19, jenis: 'Makiyah', juz: 30 },
  { id: 83, surah: 'Al Mutaffifin (83)', ayat: 36, jenis: 'Makiyah', juz: 30 },
  { id: 84, surah: 'Al Insyaq (84)', ayat: 25, jenis: 'Makiyah', juz: 30 },
  { id: 85, surah: 'Al Buruj (85)', ayat: 22, jenis: 'Makiyah', juz: 30 },
  { id: 86, surah: 'At Tariq (86)', ayat: 17, jenis: 'Makiyah', juz: 30 },
  { id: 87, surah: 'Al A’la (87)', ayat: 19, jenis: 'Makiyah', juz: 30 },
  { id: 88, surah: 'Al Ghasyiyah (88)', ayat: 26, jenis: 'Makiyah', juz: 30 },
  { id: 89, surah: 'Al Fajr (89)', ayat: 30, jenis: 'Makiyah', juz: 30 },
  { id: 90, surah: 'Al Balad (90)', ayat: 20, jenis: 'Makiyah', juz: 30 },
  { id: 91, surah: 'Asy Syams (91)', ayat: 15, jenis: 'Makiyah', juz: 30 },
  { id: 92, surah: 'Al Lail (92)', ayat: 21, jenis: 'Makiyah', juz: 30 },
  { id: 93, surah: 'Ad Duha (93)', ayat: 11, jenis: 'Makiyah', juz: 30 },
  { id: 94, surah: 'Asy Syarh (94)', ayat: 8, jenis: 'Makiyah', juz: 30 },
  { id: 95, surah: 'At Tin (95)', ayat: 8, jenis: 'Makiyah', juz: 30 },
  { id: 96, surah: 'Al ‘Alaq (96)', ayat: 19, jenis: 'Makiyah', juz: 30 },
  { id: 97, surah: 'Al Qadr (97)', ayat: 5, jenis: 'Makiyah', juz: 30 },
  { id: 98, surah: 'Al Bayyinah (98)', ayat: 8, jenis: 'Madaniyah', juz: 30 },
  { id: 99, surah: 'Az Zalzalah (99)', ayat: 8, jenis: 'Madaniyah', juz: 30 },
  { id: 100, surah: 'Al Adiyat (100)', ayat: 11, jenis: 'Makiyah', juz: 30 },
  { id: 101, surah: 'Al Qari’ah (101)', ayat: 11, jenis: 'Makiyah', juz: 30 },
  { id: 102, surah: 'At Takatsur (102)', ayat: 8, jenis: 'Makiyah', juz: 30 },
  { id: 103, surah: 'Al ‘Asr (103)', ayat: 3, jenis: 'Makiyah', juz: 30 },
  { id: 104, surah: 'Al Humazah (104)', ayat: 9, jenis: 'Makiyah', juz: 30 },
  { id: 105, surah: 'Al Fil (105)', ayat: 5, jenis: 'Makiyah', juz: 30 },
  { id: 106, surah: 'Quraisy (106)', ayat: 4, jenis: 'Makiyah', juz: 30 },
  { id: 107, surah: 'Al Maun (107)', ayat: 7, jenis: 'Makiyah', juz: 30 },
  { id: 108, surah: 'Al Kautsar (108)', ayat: 3, jenis: 'Makiyah', juz: 30 },
  { id: 109, surah: 'Al Kafirun (109)', ayat: 6, jenis: 'Makiyah', juz: 30 },
  { id: 110, surah: 'An Nasr (110)', ayat: 3, jenis: 'Madaniyah', juz: 30 },
  { id: 111, surah: 'Al Lahab (111)', ayat: 5, jenis: 'Makiyah', juz: 30 },
  { id: 112, surah: 'Al Ikhlas (112)', ayat: 4, jenis: 'Makiyah', juz: 30 },
  { id: 113, surah: 'Al Falaq (113)', ayat: 5, jenis: 'Makiyah', juz: 30 },
  { id: 114, surah: 'An Nas (114)', ayat: 6, jenis: 'Makiyah', juz: 30 },
];

export const defaultPencapaianItem: PenilaianDoaHadist = {
  judul: '',
  pencapaian: 'Berkembang',
  keterangan: '',
};
